FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY FileHubBackendV2/FileHubBackendV2.csproj FileHubBackendV2/
RUN dotnet restore FileHubBackendV2/FileHubBackendV2.csproj
COPY . .
WORKDIR /src/FileHubBackendV2
RUN dotnet build FileHubBackendV2.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish FileHubBackendV2.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "FileHubBackendV2.dll"]
