version: '3.4'

networks:
    filehub-network:
        driver: bridge

services:
  filehubbackendv2:
    build:
      context: .
      dockerfile: Dockerfile
    image: fredywhatley/filehubbackendv2
    depends_on:
      - "postgres_image"
    ports:
        - "5000:80"
    environment:
        DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=filehub_db;username=filehub_owner;password=filehub_owner_password"
    networks:
        - filehub-network
  
  postgres_image:
    image: postgres:11.3
    ports:
      - "5433"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
    environment:
      POSTGRES_USER: "filehub_owner"
      POSTGRES_PASSWORD: "filehub_owner_password"
      POSTGRES_DB: "filehub_db"
    networks:
      - filehub-network
volumes:
  db_volume:
       
# adapted from
# https://app.pluralsight.com/player?course=docker-images-containers-aspdotnet-core&author=wes-mcclure&name=docker-images-containers-aspdotnet-core-m7&clip=7&mode=live
